title = "定的随笔"

baseURL = "https://yaq.netlify.app"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

# theme = "hugo-theme-learn" # for local
theme = "github.com/matcornic/hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "mine"

editURL = "https://github.com/zrcoder/ding/tree/master/content/"
author = "ding"
description = "Ding's essays"
showVisitedLinks = false
disableSearch = false
disableAssetsBusting = false
disableInlineCopyToClipBoard = true
disableShortcutsTitle = false
disableLandingPageButton = true
disableLanguageSwitchingButton = false
disableBreadcrumb = false
disableMermaid = false
disableNextPrev = false
ordersectionsby = "time"
titleSeparator = "::"
