title = "定的随笔"
baseURL = "https://yaq.netlify.app"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

theme = "github.com/McShelby/hugo-theme-relearn"

[markup]
[markup.highlight]
noClasses = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
# theme hugo-theme-relearn: https://mcshelby.github.io/hugo-theme-relearn/basics/configuration/index.html
themeVariant = "relearn-dark"
editURL = "https://github.com/zrcoder/ding/tree/master/content/"
author = "ding"
description = "Ding's essays"
collapsibleMenu = true
disableNextPrev = true
disableLandingPageButton = true
disableInlineCopyToClipBoard = true
alwaysopen = true
disableMathJax = true
disableMermaid = true
disableOpenapi = true
additionalContentLanguage = ["en"]
