title = "定的随笔"

baseURL = "https://rdor.gitee.io/essays"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "mine"

editURL = "https://gitee.com/rdor/essays/edit/main/content/"
author = "rdor"
description = "Ding's essays"
showVisitedLinks = false
disableSearch = false
disableAssetsBusting = false
disableInlineCopyToClipBoard = true
disableShortcutsTitle = false
disableLandingPageButton = true
disableLanguageSwitchingButton = false
disableBreadcrumb = false
disableMermaid = false
customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
disableNextPrev = false
ordersectionsby = "weight"
titleSeparator = "::"

